#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function

import sys
import os

import logging
import click

import gettext
import platform

import scm


if platform.system().lower() == 'windows':
    import locale
    if os.getenv('LANG') is None:
        lang, enc = locale.getdefaultlocale()
        os.environ['LANG'] = lang
gettext.install(
    'pythource',
    os.path.join(os.path.dirname(os.path.abspath(".")), 'locale'),
    unicode=True)


@click.group(help=_('''
    Tool for generation gource's log and video from git repositories with submodules.
    '''))
@click.option('--verbose', '-v', is_flag=True, help=_('Verbose log'))
@click.option(
    '--root',
    default=os.path.dirname("."),
    type=click.Path(),
    help=_('Root repository dir'))
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_context
def pythource(ctx, verbose, root):
    setup_logger(logging.DEBUG if verbose else logging.INFO)
    ctx.obj = {
        'root': root
    }


# commands

@pythource.command(name="show", help=_('''
    Call gource for showing magic, get history range start-rev[..end-rev(def:HEAD)]
    '''))
@click.option('--start-rev', '-sr', nargs=1, help='Start revision root repo, for calculate history')
@click.option('--end-rev', '-er', default="HEAD", help='End revision root repo, for calculate history')
@click.option('--dumped-authors', '-da', default=None,
              help='Yaml format authors list. If None willl be autogenerated from git history. See dump-authors')
@click.option('--dumped-submodules', '-ds', default=None,
              help='''Yaml format submodules exclude-include. If None will be inlcude all submodules.
               See dump-submodules.''')
@click.option('--dumped-log', '-dl', default=None,
              help='''Gource format log. If None will be autogenerated with info from authors and submodules.
              See dump-log. See https://github.com/acaudwell/Gource/wiki/Custom-Log-Format''')
@click.option('--dumped-config', '-dc', default=None,
              help='''Gource format config for this visualization. Will be autosave.
              See dump-gource-config. See gource --help and gource -H''')
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_obj
def show(config, start_rev, end_rev, dumped_authors, dumped_submodules, dumped_log, dumped_config):
    scm.show(config, start_rev, end_rev, dumped_authors, dumped_submodules, dumped_log, dumped_config)


@pythource.command(name="dump-video", help=_('''
    Generated all tmp dumps, and show with save in ppm frames. Then call ffmpeg for convert visualization to video.
    '''))
@click.option('--dumped-config', '-dc', default=None,
              help='''Gource format log. If None will be autogenerated with info from authors and submodules.
              See dump-log. See https://github.com/acaudwell/Gource/wiki/Custom-Log-Format''')
@click.option('--video-name', '-vn', default=None,
              help='Name video file to save (must be, but something broken :( in work)')
@click.option('--dumped-ffmpeg-config', '-dfc', default=None,
              help='''ffmpeg config for convert ppm to video.''')
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_obj
def dump_video(config, dumped_config, video_name, dumped_ffmpeg_config):
    scm.dump_video(dumped_config, video_name, dumped_ffmpeg_config)


@pythource.command(name="dump-log", help=_('''
    Generate gource format log.
    See https://github.com/acaudwell/Gource/wiki/Custom-Log-Format
    '''))
@click.argument('start', nargs=1)
@click.argument('end', default="HEAD")
@click.option('--dumped-authors', '-da', default=None,
              help='Yaml format authors list. If None willl be autogenerated from git history. See dump-authors')
@click.option('--dumped-submodules', '-ds', default=None,
              help='''Yaml format submodules exclude-include. If None will be inlcude all submodules.
               See dump-submodules.''')
@click.option('--dumped-log', '-dl', default=None,
              help='''File for save generated gource format log.
              See https://github.com/acaudwell/Gource/wiki/Custom-Log-Format''')
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_obj
def dump_log(config, start, end, dumped_authors, dumped_submodules, dumped_log):
    scm.dump_log(config, start, end, dumped_authors, dumped_submodules, dumped_log)


@pythource.command(name="history-repos-list", help=_('''
    List of info (start-hash end-hash repo-name) for all submodules, between start-rev[..end-rev(def: HEAD)]
    on root repo
    '''))
@click.option('--start-rev', '-sr')
@click.option('--end-rev', '-er', default="HEAD")
@click.option('--list-dst', '-ld', help=_('file to save info'), default=None)
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_obj
def history_repos_list(config, start_rev, end_rev, list_dst):
    scm.history_repos_list(config, start_rev, end_rev, list_dst)


@pythource.command(name="dump-submodules", help=_('''
    Collect all submodules in repo, and write in file(--config-dst || -cd) or print part configs: allinclusive
    '''))
@click.option('--dumped-submodules', '-ds', default=None,
              help=_('file to save allinclusive'))
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_obj
def dump_submodules(config, dumped_submodules):
    scm.dump_submodules(config, dumped_submodules)


@pythource.command(name="dump-authors", help=_('''
    Collect all authors commit in all repos (or from file after command collect_submodules)
    '''))
@click.argument('start', nargs=1)
@click.argument('end', default="HEAD")
@click.option('--dumped-authors', '-da', help=_('file to save authors list'), default=None)
@click.option('--dumped-submodules', '-ds', default=None,
              help='''Yaml format submodules exclude-include. If None will be inlcude all submodules.
               See dump-submodules.''')
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_obj
def dump_authors(config, dumped_authors, dumped_submodules, start, end):
    scm.dump_authors(config, dumped_authors, dumped_submodules, start, end)


@pythource.command(name="dump-gource-config", help=_('''
    Generate and save default config for gource.
    '''))
def dump_gource_config():
    scm.dump_gource_config()


@pythource.command(help=_('''
    Print help for specified command.
    '''))
@click.argument('command-name', nargs=1)
@click.help_option('--help', '-h', help=_('Show this message and exit.'))
@click.pass_context
def help(ctx, command_name):
    if command_name in pythource.commands:
        cmd = pythource.commands[command_name]
        cmd_ctx = click.Context(cmd, parent=ctx.parent, info_name=command_name)
        print(cmd.get_help(cmd_ctx))
    else:
        raise click.BadParameter(_("No such command '{0}'").format(
            help.params[0].human_readable_name))


def setup_logger(log_level=logging.INFO):
    logging.getLogger().setLevel(logging.DEBUG)

    # class ClickStreamHandler(logging.StreamHandler):
    #     def emit(self, record):
    #         try:
    #             click.echo(self.format(record), file=self.stream)
    #             self.flush()
    #         except (KeyboardInterrupt, SystemExit):
    #             raise
    #         except:
    #             self.handleError(record)
    #
    # stream_handler = ClickStreamHandler()
    # stream_handler.setLevel(log_level)
    # logging.getLogger().addHandler(stream_handler)


def main():
    pythource()


if __name__ == '__main__':
    sys.exit(main())
